spring.datasource.url=jdbc:mysql://localhost:3306/spring_entreprises_DB_miniP?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate 
server.port=8088

server.servlet.context-path=/entreprises

logging.level.org.springframework.security=DEBUG

#spring.security.user.name=admin
#spring.security.user.password=123


spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8086/realms/nadia-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8086/realms/nadia-realm/protocol/openid-connect/certs